# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'NubiqKQhUB.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *

from . import res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1020, 550)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"background: #58768d;")
        self.main_stackedWidget = QStackedWidget(self.centralwidget)
        self.main_stackedWidget.setObjectName(u"main_stackedWidget")
        self.main_stackedWidget.setGeometry(QRect(40, 70, 940, 410))
        self.main_stackedWidget.setStyleSheet(u"border-radius: 10px; background: white;")
        self.home = QWidget()
        self.home.setObjectName(u"home")
        self.home.setStyleSheet(u"")
        self.site = QFrame(self.home)
        self.site.setObjectName(u"site")
        self.site.setGeometry(QRect(0, 0, 470, 340))
        self.site.setStyleSheet(u"")
        self.site.setFrameShape(QFrame.StyledPanel)
        self.site.setFrameShadow(QFrame.Raised)
        self.search_bar = QFrame(self.site)
        self.search_bar.setObjectName(u"search_bar")
        self.search_bar.setGeometry(QRect(45, 40, 380, 50))
        self.search_bar.setAutoFillBackground(False)
        self.search_bar.setStyleSheet(u"background: #f9f9f9; border-radius: 10px;")
        self.search_bar.setFrameShape(QFrame.StyledPanel)
        self.search_bar.setFrameShadow(QFrame.Raised)
        self.search_bar_input = QLineEdit(self.search_bar)
        self.search_bar_input.setObjectName(u"search_bar_input")
        self.search_bar_input.setGeometry(QRect(50, 0, 330, 50))
        font = QFont()
        font.setFamily(u"Noto Sans KR")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.search_bar_input.setFont(font)
        self.search_bar_input.setStyleSheet(u"color: #58768d;")
        self.search_bar_image = QLabel(self.search_bar)
        self.search_bar_image.setObjectName(u"search_bar_image")
        self.search_bar_image.setGeometry(QRect(0, 0, 50, 50))
        self.search_bar_image.setStyleSheet(u"#search_bar__image{background-color: rgba(255, 255, 255, 0); border-top-left-radius: 10px; border-bottom-left-radius: 10px;}")
        self.search_bar_image.setPixmap(QPixmap(u":/main_content/main_content/search.png"))
        self.search_bar_image.setAlignment(Qt.AlignCenter)
        self.site_stackedWidget = QStackedWidget(self.site)
        self.site_stackedWidget.setObjectName(u"site_stackedWidget")
        self.site_stackedWidget.setGeometry(QRect(45, 130, 380, 170))
        self.site_stackedWidget.setStyleSheet(u"background: #f9f9f9;")
        self.site_eleven = QWidget()
        self.site_eleven.setObjectName(u"site_eleven")
        self.site_eleven.setStyleSheet(u"")
        self.eleven_image = QLabel(self.site_eleven)
        self.eleven_image.setObjectName(u"eleven_image")
        self.eleven_image.setGeometry(QRect(120, 15, 140, 140))
        self.eleven_image.setStyleSheet(u"")
        self.eleven_image.setPixmap(QPixmap(u":/site/site/eleven.png"))
        self.eleven_image.setAlignment(Qt.AlignCenter)
        self.eleven_left_button = QPushButton(self.site_eleven)
        self.eleven_left_button.setObjectName(u"eleven_left_button")
        self.eleven_left_button.setGeometry(QRect(35, 60, 50, 50))
        self.eleven_left_button.setStyleSheet(u"QPushButton{padding-left: 15px;} QPushButton:hover{background: #cccccc; border-radius: 5px;}")
        icon = QIcon()
        icon.addFile(u":/menu/menu/left.png", QSize(), QIcon.Normal, QIcon.Off)
        self.eleven_left_button.setIcon(icon)
        self.eleven_left_button.setIconSize(QSize(30, 30))
        self.site_stackedWidget.addWidget(self.site_eleven)
        self.site_coupang = QWidget()
        self.site_coupang.setObjectName(u"site_coupang")
        self.coupang_image = QLabel(self.site_coupang)
        self.coupang_image.setObjectName(u"coupang_image")
        self.coupang_image.setGeometry(QRect(120, 15, 140, 140))
        self.coupang_image.setStyleSheet(u"")
        self.coupang_image.setPixmap(QPixmap(u":/site/site/Coupang.png"))
        self.coupang_image.setAlignment(Qt.AlignCenter)
        self.coupang_right_button = QPushButton(self.site_coupang)
        self.coupang_right_button.setObjectName(u"coupang_right_button")
        self.coupang_right_button.setGeometry(QRect(295, 60, 50, 50))
        self.coupang_right_button.setStyleSheet(u"QPushButton:hover{background: #cccccc; border-radius: 5px;}")
        icon1 = QIcon()
        icon1.addFile(u":/menu/menu/right.png", QSize(), QIcon.Normal, QIcon.Off)
        self.coupang_right_button.setIcon(icon1)
        self.coupang_right_button.setIconSize(QSize(30, 30))
        self.site_stackedWidget.addWidget(self.site_coupang)
        self.site_naver = QWidget()
        self.site_naver.setObjectName(u"site_naver")
        self.naver_left_button = QPushButton(self.site_naver)
        self.naver_left_button.setObjectName(u"naver_left_button")
        self.naver_left_button.setGeometry(QRect(35, 60, 50, 50))
        self.naver_left_button.setStyleSheet(u"QPushButton{padding-left: 15px;} QPushButton:hover{background: #cccccc; border-radius: 5px;}")
        self.naver_left_button.setIcon(icon)
        self.naver_left_button.setIconSize(QSize(30, 30))
        self.nave_image = QLabel(self.site_naver)
        self.nave_image.setObjectName(u"nave_image")
        self.nave_image.setGeometry(QRect(120, 15, 140, 140))
        self.nave_image.setStyleSheet(u"")
        self.nave_image.setPixmap(QPixmap(u":/site/site/Naver.png"))
        self.nave_image.setAlignment(Qt.AlignCenter)
        self.naver_right_button = QPushButton(self.site_naver)
        self.naver_right_button.setObjectName(u"naver_right_button")
        self.naver_right_button.setGeometry(QRect(295, 60, 50, 50))
        self.naver_right_button.setStyleSheet(u"QPushButton:hover{background: #cccccc; border-radius: 5px;}")
        self.naver_right_button.setIcon(icon1)
        self.naver_right_button.setIconSize(QSize(30, 30))
        self.site_stackedWidget.addWidget(self.site_naver)
        self.set_condition = QFrame(self.home)
        self.set_condition.setObjectName(u"set_condition")
        self.set_condition.setGeometry(QRect(470, 0, 470, 340))
        self.set_condition.setStyleSheet(u"#set_condition{border-left: 2px solid #efefef; border-top-left-radius: 0px; border-bottom-left-radius: 0px; border-bottom-right-radius: 0px;}")
        self.set_condition.setFrameShape(QFrame.StyledPanel)
        self.set_condition.setFrameShadow(QFrame.Raised)
        self.set_tabWidget = QTabWidget(self.set_condition)
        self.set_tabWidget.setObjectName(u"set_tabWidget")
        self.set_tabWidget.setGeometry(QRect(45, 40, 380, 260))
        font1 = QFont()
        font1.setPointSize(9)
        self.set_tabWidget.setFont(font1)
        self.set_tabWidget.setStyleSheet(u"QTabBar::tab {font-weight: bold; padding: 12px 18px; border-top-left-radius: 10px; border-top-right-radius: 10px; background: #cccccc;} QTabBar::tab:selected {background: #58768d; color: white;}")
        self.set_tabWidget.setUsesScrollButtons(True)
        self.set = QWidget()
        self.set.setObjectName(u"set")
        self.set.setStyleSheet(u"background: #f9f9f9;")
        self.groupBox = QGroupBox(self.set)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 0, 378, 222))
        self.groupBox.setStyleSheet(u"")
        self.recommend = QFrame(self.groupBox)
        self.recommend.setObjectName(u"recommend")
        self.recommend.setGeometry(QRect(24, 10, 330, 60))
        self.recommend.setStyleSheet(u"border-radius: none; border-bottom: 1px solid #cccccc;")
        self.recommend.setFrameShape(QFrame.StyledPanel)
        self.recommend.setFrameShadow(QFrame.Raised)
        self.recommend_id = QLabel(self.recommend)
        self.recommend_id.setObjectName(u"recommend_id")
        self.recommend_id.setGeometry(QRect(0, 0, 50, 60))
        self.recommend_id.setFont(font)
        self.recommend_id.setStyleSheet(u"color: #58768d;")
        self.recommend_id.setAlignment(Qt.AlignCenter)
        self.recommend_image = QLabel(self.recommend)
        self.recommend_image.setObjectName(u"recommend_image")
        self.recommend_image.setGeometry(QRect(50, 0, 50, 60))
        self.recommend_image.setPixmap(QPixmap(u":/main_content/main_content/recommend.png"))
        self.recommend_image.setAlignment(Qt.AlignCenter)
        self.recommend_text = QLabel(self.recommend)
        self.recommend_text.setObjectName(u"recommend_text")
        self.recommend_text.setGeometry(QRect(100, 0, 230, 60))
        self.recommend_text.setFont(font)
        self.recommend_text.setStyleSheet(u"color: #58768d;")
        self.recommend_text.setAlignment(Qt.AlignCenter)
        self.recommend_button = QRadioButton(self.recommend)
        self.recommend_button.setObjectName(u"recommend_button")
        self.recommend_button.setGeometry(QRect(0, 0, 330, 60))
        self.recommend_button.setStyleSheet(u"QRadioButton::indicator{width: 0px; height: 0px;} QRadioButton{background-color: rgba(0, 0, 0, 0); border-radius: 5px;} QRadioButton:hover{background-color: rgba(0, 0, 0, 50); border-bottom-left-radius: 0px; border-bottom-right-radius: 0px;} QRadioButton:checked{background-color: rgba(0, 0, 0, 50); border-bottom-left-radius: 0px; border-bottom-right-radius: 0px;}")
        self.recommend_text.raise_()
        self.recommend_id.raise_()
        self.recommend_image.raise_()
        self.recommend_button.raise_()
        self.sales = QFrame(self.groupBox)
        self.sales.setObjectName(u"sales")
        self.sales.setGeometry(QRect(24, 82, 330, 60))
        self.sales.setStyleSheet(u"border-radius: none; border-bottom: 1px solid #cccccc;")
        self.sales.setFrameShape(QFrame.StyledPanel)
        self.sales.setFrameShadow(QFrame.Raised)
        self.sales_id = QLabel(self.sales)
        self.sales_id.setObjectName(u"sales_id")
        self.sales_id.setGeometry(QRect(0, 0, 50, 60))
        self.sales_id.setFont(font)
        self.sales_id.setStyleSheet(u"color: #58768d;")
        self.sales_id.setAlignment(Qt.AlignCenter)
        self.sales_image = QLabel(self.sales)
        self.sales_image.setObjectName(u"sales_image")
        self.sales_image.setGeometry(QRect(50, 0, 50, 60))
        self.sales_image.setPixmap(QPixmap(u":/main_content/main_content/sales.png"))
        self.sales_image.setAlignment(Qt.AlignCenter)
        self.sales_text = QLabel(self.sales)
        self.sales_text.setObjectName(u"sales_text")
        self.sales_text.setGeometry(QRect(100, 0, 230, 60))
        self.sales_text.setFont(font)
        self.sales_text.setStyleSheet(u"color: #58768d;")
        self.sales_text.setAlignment(Qt.AlignCenter)
        self.sales_button = QRadioButton(self.sales)
        self.sales_button.setObjectName(u"sales_button")
        self.sales_button.setGeometry(QRect(0, 0, 330, 60))
        self.sales_button.setStyleSheet(u"QRadioButton::indicator{width: 0px; height: 0px;} QRadioButton{background-color: rgba(0, 0, 0, 0); border-radius: 5px;} QRadioButton:hover{background-color: rgba(0, 0, 0, 50); border-bottom-left-radius: 0px; border-bottom-right-radius: 0px;} QRadioButton:checked{background-color: rgba(0, 0, 0, 50); border-bottom-left-radius: 0px; border-bottom-right-radius: 0px;}")
        self.newest = QFrame(self.groupBox)
        self.newest.setObjectName(u"newest")
        self.newest.setGeometry(QRect(24, 152, 330, 60))
        self.newest.setStyleSheet(u"")
        self.newest.setFrameShape(QFrame.StyledPanel)
        self.newest.setFrameShadow(QFrame.Raised)
        self.newest_id = QLabel(self.newest)
        self.newest_id.setObjectName(u"newest_id")
        self.newest_id.setGeometry(QRect(0, 0, 50, 60))
        self.newest_id.setFont(font)
        self.newest_id.setStyleSheet(u"color: #58768d;")
        self.newest_id.setAlignment(Qt.AlignCenter)
        self.newest_image = QLabel(self.newest)
        self.newest_image.setObjectName(u"newest_image")
        self.newest_image.setGeometry(QRect(50, 0, 50, 60))
        self.newest_image.setPixmap(QPixmap(u":/main_content/main_content/newest.png"))
        self.newest_image.setAlignment(Qt.AlignCenter)
        self.newest_text = QLabel(self.newest)
        self.newest_text.setObjectName(u"newest_text")
        self.newest_text.setGeometry(QRect(100, 0, 230, 60))
        self.newest_text.setFont(font)
        self.newest_text.setStyleSheet(u"color: #58768d;")
        self.newest_text.setAlignment(Qt.AlignCenter)
        self.newest_button = QRadioButton(self.newest)
        self.newest_button.setObjectName(u"newest_button")
        self.newest_button.setGeometry(QRect(0, 0, 330, 60))
        self.newest_button.setStyleSheet(u"QRadioButton::indicator{width: 0px; height: 0px;} QRadioButton{background-color: rgba(0, 0, 0, 0); border-radius: 5px;} QRadioButton:hover{background-color: rgba(0, 0, 0, 50); border-bottom-left-radius: 0px; border-bottom-right-radius: 0px;} QRadioButton:checked{background-color: rgba(0, 0, 0, 50); border-bottom-left-radius: 0px; border-bottom-right-radius: 0px;}")
        self.set_tabWidget.addTab(self.set, "")
        self.action = QWidget()
        self.action.setObjectName(u"action")
        self.action.setStyleSheet(u"background: #f9f9f9;")
        self.page = QFrame(self.action)
        self.page.setObjectName(u"page")
        self.page.setGeometry(QRect(30, 20, 330, 65))
        self.page.setStyleSheet(u"#page{border-radius: none; border-bottom: 1px solid #cccccc;}")
        self.page.setFrameShape(QFrame.StyledPanel)
        self.page.setFrameShadow(QFrame.Raised)
        self.page_id = QLabel(self.page)
        self.page_id.setObjectName(u"page_id")
        self.page_id.setGeometry(QRect(0, 0, 50, 60))
        self.page_id.setFont(font)
        self.page_id.setStyleSheet(u"color: #58768d;")
        self.page_id.setAlignment(Qt.AlignCenter)
        self.page_image = QLabel(self.page)
        self.page_image.setObjectName(u"page_image")
        self.page_image.setGeometry(QRect(50, 0, 50, 60))
        self.page_image.setPixmap(QPixmap(u":/main_content/main_content/page.png"))
        self.page_image.setAlignment(Qt.AlignCenter)
        self.page_input_text = QLineEdit(self.page)
        self.page_input_text.setObjectName(u"page_input_text")
        self.page_input_text.setGeometry(QRect(100, 0, 230, 60))
        self.page_input_text.setFont(font)
        self.page_input_text.setStyleSheet(u"color: #58768d; background: #efefef;")
        self.page_input_text.setAlignment(Qt.AlignCenter)
        self.start = QFrame(self.action)
        self.start.setObjectName(u"start")
        self.start.setGeometry(QRect(30, 95, 330, 60))
        self.start.setStyleSheet(u"")
        self.start.setFrameShape(QFrame.StyledPanel)
        self.start.setFrameShadow(QFrame.Raised)
        self.start_id = QLabel(self.start)
        self.start_id.setObjectName(u"start_id")
        self.start_id.setGeometry(QRect(0, 0, 50, 60))
        self.start_id.setFont(font)
        self.start_id.setStyleSheet(u"color: #58768d;")
        self.start_id.setAlignment(Qt.AlignCenter)
        self.start_image = QLabel(self.start)
        self.start_image.setObjectName(u"start_image")
        self.start_image.setGeometry(QRect(50, 0, 50, 60))
        self.start_image.setPixmap(QPixmap(u":/main_content/main_content/start.png"))
        self.start_image.setAlignment(Qt.AlignCenter)
        self.start_button = QPushButton(self.start)
        self.start_button.setObjectName(u"start_button")
        self.start_button.setGeometry(QRect(100, 0, 230, 60))
        self.start_button.setFont(font)
        self.start_button.setStyleSheet(u"QPushButton{background: #efefef; color: black;} QPushButton:hover{background: #58768d; color: white} ")
        self.set_tabWidget.addTab(self.action, "")
        self.menu = QFrame(self.home)
        self.menu.setObjectName(u"menu")
        self.menu.setGeometry(QRect(0, 340, 940, 70))
        self.menu.setStyleSheet(u"background: #efefef; border-top-left-radius: 0px; border-top-right-radius: 0px;")
        self.menu.setFrameShape(QFrame.StyledPanel)
        self.menu.setFrameShadow(QFrame.Raised)
        self.help = QPushButton(self.menu)
        self.help.setObjectName(u"help")
        self.help.setGeometry(QRect(445, 10, 50, 50))
        self.help.setStyleSheet(u"QPushButton{background-color: rgba(255, 255, 255, 0);} QPushButton::hover{background: #cccccc; border-radius: 10px;}")
        icon2 = QIcon()
        icon2.addFile(u":/menu/menu/help.png", QSize(), QIcon.Normal, QIcon.Off)
        self.help.setIcon(icon2)
        self.help.setIconSize(QSize(40, 40))
        self.download = QPushButton(self.menu)
        self.download.setObjectName(u"download")
        self.download.setGeometry(QRect(200, 10, 50, 50))
        self.download.setStyleSheet(u"QPushButton{background-color: rgba(255, 255, 255, 0);} QPushButton::hover{background: #cccccc; border-radius: 10px;}")
        icon3 = QIcon()
        icon3.addFile(u":/menu/menu/download.png", QSize(), QIcon.Normal, QIcon.Off)
        self.download.setIcon(icon3)
        self.download.setIconSize(QSize(40, 40))
        self.setting = QPushButton(self.menu)
        self.setting.setObjectName(u"setting")
        self.setting.setGeometry(QRect(690, 10, 50, 50))
        self.setting.setStyleSheet(u"QPushButton{background-color: rgba(255, 255, 255, 0);} QPushButton::hover{background: #cccccc; border-radius: 10px;}")
        icon4 = QIcon()
        icon4.addFile(u":/menu/menu/setting.png", QSize(), QIcon.Normal, QIcon.Off)
        self.setting.setIcon(icon4)
        self.setting.setIconSize(QSize(40, 40))
        self.main_stackedWidget.addWidget(self.home)
        self.info = QWidget()
        self.info.setObjectName(u"info")
        self.info_card = QFrame(self.info)
        self.info_card.setObjectName(u"info_card")
        self.info_card.setGeometry(QRect(170, 10, 600, 390))
        self.info_card.setFrameShape(QFrame.StyledPanel)
        self.info_card.setFrameShadow(QFrame.Raised)
        self.info_headline = QLabel(self.info_card)
        self.info_headline.setObjectName(u"info_headline")
        self.info_headline.setGeometry(QRect(200, 20, 200, 30))
        font2 = QFont()
        font2.setFamily(u"KoPub\ub3cb\uc6c0\uccb4 Medium")
        font2.setPointSize(16)
        font2.setBold(False)
        font2.setWeight(50)
        self.info_headline.setFont(font2)
        self.info_headline.setStyleSheet(u"background-color: rgba(255, 255, 255, 0); color: #56748C;")
        self.info_headline.setAlignment(Qt.AlignCenter)
        self.left_info = QFrame(self.info_card)
        self.left_info.setObjectName(u"left_info")
        self.left_info.setGeometry(QRect(100, 80, 400, 80))
        self.left_info.setFrameShape(QFrame.StyledPanel)
        self.left_info.setFrameShadow(QFrame.Raised)
        self.left_detail = QLabel(self.left_info)
        self.left_detail.setObjectName(u"left_detail")
        self.left_detail.setGeometry(QRect(0, 0, 80, 30))
        self.left_detail.setFont(font)
        self.left_detail.setStyleSheet(u"background-color: rgba(255, 255, 255, 0); color: #56748C;")
        self.left_detail.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.info_search = QLabel(self.left_info)
        self.info_search.setObjectName(u"info_search")
        self.info_search.setGeometry(QRect(0, 40, 400, 15))
        font3 = QFont()
        font3.setFamily(u"Noto Sans KR")
        font3.setPointSize(10)
        font3.setBold(True)
        font3.setWeight(75)
        self.info_search.setFont(font3)
        self.info_search.setStyleSheet(u"background-color: rgba(255, 255, 255, 0); color: #56748C;")
        self.info_search.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.info_site = QLabel(self.left_info)
        self.info_site.setObjectName(u"info_site")
        self.info_site.setGeometry(QRect(0, 65, 400, 15))
        self.info_site.setFont(font3)
        self.info_site.setStyleSheet(u"background-color: rgba(255, 255, 255, 0); color: #56748C;")
        self.info_site.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.right_info = QFrame(self.info_card)
        self.right_info.setObjectName(u"right_info")
        self.right_info.setGeometry(QRect(100, 180, 400, 80))
        self.right_info.setFrameShape(QFrame.StyledPanel)
        self.right_info.setFrameShadow(QFrame.Raised)
        self.right_detail = QLabel(self.right_info)
        self.right_detail.setObjectName(u"right_detail")
        self.right_detail.setGeometry(QRect(0, 0, 80, 30))
        self.right_detail.setFont(font)
        self.right_detail.setStyleSheet(u"background-color: rgba(255, 255, 255, 0); color: #56748C;")
        self.right_detail.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.info_set_codition = QLabel(self.right_info)
        self.info_set_codition.setObjectName(u"info_set_codition")
        self.info_set_codition.setGeometry(QRect(0, 40, 400, 15))
        self.info_set_codition.setFont(font3)
        self.info_set_codition.setStyleSheet(u"background-color: rgba(255, 255, 255, 0); color: #56748C;")
        self.info_set_codition.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.info_page = QLabel(self.right_info)
        self.info_page.setObjectName(u"info_page")
        self.info_page.setGeometry(QRect(0, 65, 400, 15))
        self.info_page.setFont(font3)
        self.info_page.setStyleSheet(u"background-color: rgba(255, 255, 255, 0); color: #56748C;")
        self.info_page.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.strat_info = QFrame(self.info_card)
        self.strat_info.setObjectName(u"strat_info")
        self.strat_info.setGeometry(QRect(100, 280, 400, 55))
        self.strat_info.setFrameShape(QFrame.StyledPanel)
        self.strat_info.setFrameShadow(QFrame.Raised)
        self.start_detail = QLabel(self.strat_info)
        self.start_detail.setObjectName(u"start_detail")
        self.start_detail.setGeometry(QRect(0, 0, 80, 30))
        self.start_detail.setFont(font)
        self.start_detail.setStyleSheet(u"background-color: rgba(255, 255, 255, 0); color: #56748C;")
        self.start_detail.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.info_start = QLabel(self.strat_info)
        self.info_start.setObjectName(u"info_start")
        self.info_start.setGeometry(QRect(0, 40, 400, 15))
        self.info_start.setFont(font3)
        self.info_start.setStyleSheet(u"background-color: rgba(255, 255, 255, 0); color: #56748C;")
        self.info_start.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.info_prev_button = QPushButton(self.info)
        self.info_prev_button.setObjectName(u"info_prev_button")
        self.info_prev_button.setGeometry(QRect(10, 10, 50, 50))
        self.info_prev_button.setStyleSheet(u"QPushButton{padding-left: 10px;} QPushButton:hover{background: #cccccc; border-radius: 5px; padding-left: 10px}")
        self.info_prev_button.setIcon(icon)
        self.info_prev_button.setIconSize(QSize(30, 30))
        self.main_stackedWidget.addWidget(self.info)
        self.coming_soon = QWidget()
        self.coming_soon.setObjectName(u"coming_soon")
        self.coming_soon_card = QFrame(self.coming_soon)
        self.coming_soon_card.setObjectName(u"coming_soon_card")
        self.coming_soon_card.setGeometry(QRect(270, 55, 400, 300))
        self.coming_soon_card.setFrameShape(QFrame.StyledPanel)
        self.coming_soon_card.setFrameShadow(QFrame.Raised)
        self.coming_soon_image = QLabel(self.coming_soon_card)
        self.coming_soon_image.setObjectName(u"coming_soon_image")
        self.coming_soon_image.setGeometry(QRect(135, 10, 130, 130))
        self.coming_soon_image.setPixmap(QPixmap(u":/logo/logo/large_logo.png"))
        self.coming_soon_image.setAlignment(Qt.AlignCenter)
        self.coming_soon_name = QLabel(self.coming_soon_card)
        self.coming_soon_name.setObjectName(u"coming_soon_name")
        self.coming_soon_name.setGeometry(QRect(135, 130, 130, 30))
        font4 = QFont()
        font4.setFamily(u"Arial Rounded MT Bold")
        font4.setPointSize(16)
        font4.setBold(False)
        font4.setWeight(50)
        self.coming_soon_name.setFont(font4)
        self.coming_soon_name.setStyleSheet(u"background-color: rgba(255, 255, 255, 0); color: #56748C;")
        self.coming_soon_name.setAlignment(Qt.AlignCenter)
        self.coming_soon_detail_first = QLabel(self.coming_soon_card)
        self.coming_soon_detail_first.setObjectName(u"coming_soon_detail_first")
        self.coming_soon_detail_first.setGeometry(QRect(50, 250, 300, 15))
        font5 = QFont()
        font5.setFamily(u"KoPub\ub3cb\uc6c0\uccb4 Medium")
        font5.setPointSize(10)
        font5.setBold(False)
        font5.setWeight(50)
        self.coming_soon_detail_first.setFont(font5)
        self.coming_soon_detail_first.setStyleSheet(u"background-color: rgba(255, 255, 255, 0); color: #56748C;")
        self.coming_soon_detail_first.setAlignment(Qt.AlignCenter)
        self.coming_soon_headline = QLabel(self.coming_soon_card)
        self.coming_soon_headline.setObjectName(u"coming_soon_headline")
        self.coming_soon_headline.setGeometry(QRect(50, 200, 300, 30))
        self.coming_soon_headline.setFont(font2)
        self.coming_soon_headline.setStyleSheet(u"background-color: rgba(255, 255, 255, 0); color: #56748C;")
        self.coming_soon_headline.setAlignment(Qt.AlignCenter)
        self.coming_soon_detail_second = QLabel(self.coming_soon_card)
        self.coming_soon_detail_second.setObjectName(u"coming_soon_detail_second")
        self.coming_soon_detail_second.setGeometry(QRect(50, 275, 300, 15))
        self.coming_soon_detail_second.setFont(font5)
        self.coming_soon_detail_second.setStyleSheet(u"background-color: rgba(255, 255, 255, 0); color: #56748C;")
        self.coming_soon_detail_second.setAlignment(Qt.AlignCenter)
        self.coming_soon_prev_button = QPushButton(self.coming_soon)
        self.coming_soon_prev_button.setObjectName(u"coming_soon_prev_button")
        self.coming_soon_prev_button.setGeometry(QRect(10, 10, 50, 50))
        self.coming_soon_prev_button.setStyleSheet(u"QPushButton{padding-left: 10px;} QPushButton:hover{background: #cccccc; border-radius: 5px; padding-left: 10px}")
        self.coming_soon_prev_button.setIcon(icon)
        self.coming_soon_prev_button.setIconSize(QSize(30, 30))
        self.main_stackedWidget.addWidget(self.coming_soon)
        self.progress = QWidget()
        self.progress.setObjectName(u"progress")
        self.main_stackedWidget.addWidget(self.progress)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.main_stackedWidget.setCurrentIndex(0)
        self.site_stackedWidget.setCurrentIndex(2)
        self.set_tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.search_bar_input.setText("")
        self.search_bar_input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.search_bar_image.setText("")
        self.eleven_image.setText("")
        self.eleven_left_button.setText("")
        self.coupang_image.setText("")
        self.coupang_right_button.setText("")
        self.naver_left_button.setText("")
        self.nave_image.setText("")
        self.naver_right_button.setText("")
        self.groupBox.setTitle("")
        self.recommend_id.setText(QCoreApplication.translate("MainWindow", u"01", None))
        self.recommend_image.setText("")
        self.recommend_text.setText(QCoreApplication.translate("MainWindow", u"\ucd94\ucc9c\uc21c", None))
        self.recommend_button.setText("")
        self.sales_id.setText(QCoreApplication.translate("MainWindow", u"02", None))
        self.sales_image.setText("")
        self.sales_text.setText(QCoreApplication.translate("MainWindow", u"\ud310\ub9e4\uc21c", None))
        self.sales_button.setText("")
        self.newest_id.setText(QCoreApplication.translate("MainWindow", u"03", None))
        self.newest_image.setText("")
        self.newest_text.setText(QCoreApplication.translate("MainWindow", u"\ucd5c\uc2e0\uc21c", None))
        self.newest_button.setText("")
        self.set_tabWidget.setTabText(self.set_tabWidget.indexOf(self.set), QCoreApplication.translate("MainWindow", u"\uc870\uac74 \uc124\uc815", None))
        self.page_id.setText(QCoreApplication.translate("MainWindow", u"04", None))
        self.page_image.setText("")
        self.page_input_text.setText("")
        self.page_input_text.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uc0c1\ud488 \uc218 \uc785\ub825 (\uc608: 100)", None))
        self.start_id.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.start_image.setText("")
        self.start_button.setText(QCoreApplication.translate("MainWindow", u"start", None))
        self.set_tabWidget.setTabText(self.set_tabWidget.indexOf(self.action), QCoreApplication.translate("MainWindow", u"\uc2e4\ud589 \uc124\uc815", None))
        self.help.setText("")
        self.download.setText("")
        self.setting.setText("")
        self.info_headline.setText(QCoreApplication.translate("MainWindow", u"Nubi \uc0ac\uc6a9 \uac00\uc774\ub4dc", None))
        self.left_detail.setText(QCoreApplication.translate("MainWindow", u"\uc88c\uce21 \uc124\uc815", None))
        self.info_search.setText(QCoreApplication.translate("MainWindow", u"1.   \uac80\uc0c9\ucc3d\uc5d0\uc11c '\uc0c1\ud488\uba85'\uc744 \uc785\ub825\ud574\uc8fc\uc138\uc694.", None))
        self.info_site.setText(QCoreApplication.translate("MainWindow", u"2.  \ubc84\ud2bc\uc744 \uc0ac\uc6a9\ud574 \uc0ac\uc774\ud2b8\ub97c \uc120\ud0dd\ud574\uc8fc\uc138\uc694.", None))
        self.right_detail.setText(QCoreApplication.translate("MainWindow", u"\uc6b0\uce21 \uc124\uc815", None))
        self.info_set_codition.setText(QCoreApplication.translate("MainWindow", u"1.  '\uc870\uac74 \uc124\uc815' \ud0ed\uc5d0\uc11c \uac80\uc0c9 \uae30\uc900\uc744 \uc120\ud0dd\ud574\uc8fc\uc138\uc694.", None))
        self.info_page.setText(QCoreApplication.translate("MainWindow", u"2.  '\uc2e4\ud589 \uc124\uc815' \ud0ed\uc5d0\uc11c \ud398\uc774\uc9c0 \uc218\ub97c \uc785\ub825\ud574\uc8fc\uc138\uc694.", None))
        self.start_detail.setText(QCoreApplication.translate("MainWindow", u"\uc2e4\ud589", None))
        self.info_start.setText(QCoreApplication.translate("MainWindow", u"1.  \ubaa8\ub4e0 \uc124\uc815\uc744 \uc644\ub8cc\ud55c \uc774\ud6c4 '\uc2e4\ud589 \ubc84\ud2bc'\uc744 \ud074\ub9ad\ud574\uc8fc\uc138\uc694.", None))
        self.info_prev_button.setText("")
        self.coming_soon_image.setText("")
        self.coming_soon_name.setText(QCoreApplication.translate("MainWindow", u"Nubi", None))
        self.coming_soon_detail_first.setText(QCoreApplication.translate("MainWindow", u"\uc774\uc6a9\uc5d0 \ubd88\ud3b8\uc744 \ub4dc\ub824 \ub300\ub2e8\ud788 \uc8c4\uc1a1\ud569\ub2c8\ub2e4.", None))
        self.coming_soon_headline.setText(QCoreApplication.translate("MainWindow", u"\ud604\uc7ac \uc774 \ud398\uc774\uc9c0\ub294 \uc900\ube44\uc911\uc785\ub2c8\ub2e4.", None))
        self.coming_soon_detail_second.setText(QCoreApplication.translate("MainWindow", u"\ube60\ub978 \uc2dc\uc77c \ub0b4\uc5d0 \uc900\ube44\ud558\uc5ec \ucc3e\uc544\ubd59\uaca0\uc2b5\ub2c8\ub2e4.", None))
        self.coming_soon_prev_button.setText("")
    # retranslateUi

